USE [master]
GO
/****** Object:  Database [MateusStore]    Script Date: 16/06/2020 10:42:51 ******/
CREATE DATABASE [MateusStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Test_Ithappens', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Test_Ithappens.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Test_Ithappens_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Test_Ithappens_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [MateusStore] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MateusStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MateusStore] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MateusStore] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MateusStore] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MateusStore] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MateusStore] SET ARITHABORT OFF 
GO
ALTER DATABASE [MateusStore] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MateusStore] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MateusStore] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MateusStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MateusStore] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MateusStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MateusStore] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MateusStore] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MateusStore] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MateusStore] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MateusStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MateusStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MateusStore] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MateusStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MateusStore] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MateusStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MateusStore] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MateusStore] SET RECOVERY FULL 
GO
ALTER DATABASE [MateusStore] SET  MULTI_USER 
GO
ALTER DATABASE [MateusStore] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MateusStore] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MateusStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MateusStore] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [MateusStore] SET DELAYED_DURABILITY = DISABLED 
GO
USE [MateusStore]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 16/06/2020 10:42:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Cliente](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](90) NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Estoque]    Script Date: 16/06/2020 10:42:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estoque](
	[IdProduto] [int] NOT NULL,
	[Quantidade] [int] NOT NULL,
	[CodFilial] [int] NOT NULL,
 CONSTRAINT [PK_Estoque] PRIMARY KEY CLUSTERED 
(
	[IdProduto] ASC,
	[CodFilial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Filial]    Script Date: 16/06/2020 10:42:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Filial](
	[Codigo] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](60) NOT NULL,
 CONSTRAINT [PK_Filial] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ItemPedido]    Script Date: 16/06/2020 10:42:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ItemPedido](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Pedido] [int] NOT NULL,
	[Produto] [int] NOT NULL,
	[ValorUnitario] [decimal](15, 4) NOT NULL,
	[Quantidade] [decimal](15, 4) NOT NULL,
	[ValorTotal] [decimal](15, 4) NOT NULL,
	[Status] [int] NOT NULL CONSTRAINT [DF_ItensPedido_Status]  DEFAULT ((1)),
 CONSTRAINT [PK_ItemPedido] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PedidoEstoque]    Script Date: 16/06/2020 10:42:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PedidoEstoque](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Tipo] [int] NOT NULL,
	[Origem] [int] NOT NULL,
	[Usuario] [int] NOT NULL,
	[Filial] [int] NOT NULL,
	[QuantidadeDeItens] [int] NOT NULL CONSTRAINT [DF_PedidoEstoque_TotalDeItens]  DEFAULT ((0)),
	[Valor] [decimal](15, 4) NOT NULL CONSTRAINT [DF_PedidoEstoque_Valor]  DEFAULT ((0.00)),
 CONSTRAINT [PK_PedidoEstoque] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Produto]    Script Date: 16/06/2020 10:42:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Produto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](60) NOT NULL,
	[CodBarra] [varchar](30) NOT NULL,
	[PrecoCusto] [decimal](15, 4) NOT NULL,
	[PrecoVenda] [decimal](15, 4) NOT NULL,
 CONSTRAINT [PK_Produto] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 16/06/2020 10:42:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Usuario](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](90) NOT NULL,
	[Login] [varchar](50) NOT NULL,
	[Senha] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Venda]    Script Date: 16/06/2020 10:42:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Venda](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cliente] [int] NOT NULL,
	[Observacao] [varchar](100) NULL,
	[FormaDePagamento] [int] NOT NULL,
	[PedidoEstoque] [int] NOT NULL,
 CONSTRAINT [PK_Venda] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Estoque]  WITH CHECK ADD  CONSTRAINT [FK_Filial_Estoque] FOREIGN KEY([CodFilial])
REFERENCES [dbo].[Filial] ([Codigo])
GO
ALTER TABLE [dbo].[Estoque] CHECK CONSTRAINT [FK_Filial_Estoque]
GO
ALTER TABLE [dbo].[Estoque]  WITH CHECK ADD  CONSTRAINT [FK_Produto_Estoque] FOREIGN KEY([IdProduto])
REFERENCES [dbo].[Produto] ([Id])
GO
ALTER TABLE [dbo].[Estoque] CHECK CONSTRAINT [FK_Produto_Estoque]
GO
ALTER TABLE [dbo].[ItemPedido]  WITH CHECK ADD  CONSTRAINT [FK_PedidoEstoque_ItensPedido] FOREIGN KEY([Pedido])
REFERENCES [dbo].[PedidoEstoque] ([Id])
GO
ALTER TABLE [dbo].[ItemPedido] CHECK CONSTRAINT [FK_PedidoEstoque_ItensPedido]
GO
ALTER TABLE [dbo].[ItemPedido]  WITH CHECK ADD  CONSTRAINT [FK_Produto_ItensPedido] FOREIGN KEY([Produto])
REFERENCES [dbo].[Produto] ([Id])
GO
ALTER TABLE [dbo].[ItemPedido] CHECK CONSTRAINT [FK_Produto_ItensPedido]
GO
ALTER TABLE [dbo].[PedidoEstoque]  WITH CHECK ADD  CONSTRAINT [FK_Filial_PedidoEstoque] FOREIGN KEY([Filial])
REFERENCES [dbo].[Filial] ([Codigo])
GO
ALTER TABLE [dbo].[PedidoEstoque] CHECK CONSTRAINT [FK_Filial_PedidoEstoque]
GO
ALTER TABLE [dbo].[PedidoEstoque]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_PedidoEstoque] FOREIGN KEY([Usuario])
REFERENCES [dbo].[Usuario] ([Id])
GO
ALTER TABLE [dbo].[PedidoEstoque] CHECK CONSTRAINT [FK_Usuario_PedidoEstoque]
GO
ALTER TABLE [dbo].[Venda]  WITH CHECK ADD  CONSTRAINT [FK_Cliente_Venda] FOREIGN KEY([Cliente])
REFERENCES [dbo].[Cliente] ([Id])
GO
ALTER TABLE [dbo].[Venda] CHECK CONSTRAINT [FK_Cliente_Venda]
GO
ALTER TABLE [dbo].[Venda]  WITH CHECK ADD  CONSTRAINT [FK_PedidoEstoque_Venda] FOREIGN KEY([PedidoEstoque])
REFERENCES [dbo].[PedidoEstoque] ([Id])
GO
ALTER TABLE [dbo].[Venda] CHECK CONSTRAINT [FK_PedidoEstoque_Venda]
GO
USE [master]
GO
ALTER DATABASE [MateusStore] SET  READ_WRITE 
GO
